# path to your blog's icon
favicon: /favicon.png

# path to manifest.json
manifest: /manifest.json

# [Open Graph Protocol](https://ogp.me/)
og_enabled: true
og_image: /favicon.png
og:
  # customized og properties, which can replace the defaults

# show excerpt on post list
show_excerpt: false

# default light/dark/auto color scheme
color_scheme: auto

# show color theme toggle in footer
show_color_scheme_toggle: true

# uppercase categories
uppercase_categories: true

# capitalize tag names on tags page
capitalize_tags: false

# add hashtag prefix before tags
hashtag_prefix_before_tags: true

# rainbow!
rainbow_banner: true
rainbow_banner_colors:
  - '#e50000'
  - '#ff8d00'
  - '#ffee00'
  - '#008121'
  - '#004cff'
  - '#760188'
# when to show rainbow banner: auto/always
rainbow_banner_shown: auto
# Pride Month by default
rainbow_banner_month: 6

# table of contents
toc: true
toc_max_depth: 2

# scroll reveal (https://scrollrevealjs.org/) - animating elements as they enter the viewport
scroll_reveal: true

nav:
  title: Blog
  items:
    - name: Archives
      url: /archives
    - name: Friends
      url: /friends
    - name: Projects
      url: /projects
    - name: About
      url: /about
    - name: <i class="si si-github"></i>
      is_icon: true
      url: https://github.com/MrWillCom
    - name: <i class="si si-codepen"></i>
      is_icon: true
      url: https://codepen.io/mrwillcom
    - name: <i class="si si-patreon"></i>
      is_icon: true
      url: https://www.patreon.com/MrWillCom
    - name: <i class="si si-mastodon"></i>
      is_icon: true
      url: https://noc.social/@MrWillCom
    - name: <i class="bi bi-search"></i>
      is_icon: true
      url: /search

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    Tags: /tags
    Categories: /categories
    Search: /search
    Friends: /friends
    Projects: /projects
    Resume: /resume
    About: /about
    RSS: /atom.xml
  # also the title
  Projects:
    # the items
    RSA CLI: https://github.com/MrWillCom/rsa-cli
    Hexo Theme Cupertino: https://github.com/MrWillCom/hexo-theme-cupertino
    A Calendar: https://github.com/MrWillCom/a-calendar
    Auto Mirroring Bucket: https://github.com/MrWillCom/auto-mirroring-bucket
  # the title
  Me:
    # items
    GitHub: https://github.com/MrWillCom
    CodePen: https://codepen.io/mrwillcom
    Patreon: https://www.patreon.com/MrWillCom
    Mastodon: https://noc.social/@MrWillCom
    Discord: https://discord.gg/UKuFDjcfY8
    Email: mailto:mr.will.com@outlook.com

# footer extra description
# footer_extra_description: something will be shown at the bottom of the footer

license: CC BY-NC 4.0
license_link: https://creativecommons.org/licenses/by-nc/4.0

# search
# based on [hexo-generator-search](https://github.com/wzpan/hexo-generator-search)
search: true
search_path: search.json

# icons
simple_icons: true
# Theme Cupertino requires Bootstrap Icons to display some icons of the UI, don't turn it off unless you know what exactly you're doing.
bootstrap_icons: true
# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!
